CREATE TABLE RolePermissions (
    RolePermissionID SERIAL PRIMARY KEY,
    RoleID INT NOT NULL REFERENCES Roles(RoleID) ON DELETE CASCADE,
    PermissionCode VARCHAR(100) NOT NULL,
    PermissionName VARCHAR(200),
    CanCreate BOOLEAN DEFAULT FALSE,
    CanRead BOOLEAN DEFAULT FALSE,
    CanUpdate BOOLEAN DEFAULT FALSE,
    CanDelete BOOLEAN DEFAULT FALSE,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);